//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralSetting
    {
        public System.Guid GeneralSettingID { get; set; }
        public bool EnableEmailAlert { get; set; }
        public bool EnableActionReminder { get; set; }
        public string RecipientEmails { get; set; }
        public int ActionReminderInterval { get; set; }
    }
}
