//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketFile
    {
        public System.Guid TicketFileID { get; set; }
        public System.Guid TicketID { get; set; }
        public string FileName { get; set; }
        public string FileForTOrN { get; set; }
        public System.Guid RefID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
